# Generated by Django 5.0.3 on 2024-04-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
